version: "3.5"

services:
  userstorymapping:
    image: sndregistry.sondeosglobal.com/user-story-mapping:1.0.1
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    ports:
      - "8070:5000"
    environment:
      NODE_ENV: "production"
      MONGO_URI: "mongodb://192.168.10.70:27017/user-story-mapping"
      JWT_SECRET: "V7wzw4iL9H40oxXAVj9u"
      JWT_LOGIN_EXPIRED_IN: "3d"
      JWT_REGISTER_EXPIRED_IN: "30d"
      APP_NAME: "UserStoryMapping"
      APP_PORT: 5000
      APP_API_URL: "http://192.168.10.33:8070"
      APP_WEB_URL: "http://192.168.10.33:8070"
      SMTP_HOST: "smtp.xxxx.com.ar"
      SMTP_PORT: 25
      SMTP_SECURE: "false"
      SMTP_IGNORE_TLS: "true"
      SMTP_USER: "user@domain.com.ar"
      SMTP_PASS: "xxxxxx"
      AVATAR_MAX_SIZE: 2000000
      LOG_LEVEL: "debug"
      LOG_REQUEST: "ON"
      LOG_RESPONSE_TIME: "ON"
      LOG_GQL_ERRORS: "ON"
      LOG_TRANSPORT_CONSOLE: "ON"
      LOG_TRANSPORT_COMBINED: "ON"
      LOG_TRANSPORT_ERROR: "ON"
      LOG_TRANSPORT_ACCESS: "ON"
      LOG_TRANSPORT_GQL_ERROR: "ON"
      LOG_TRANSPORT_GQL_RESPONSE: "ON"
      LOG_COLORIZE: "ON"
      LOG_FILE_MAX_SIZE: 50000000
      LOG_FILE_MAX_FILES: 3
      LOG_MODE: "TEXT"
